output: ./output_dir
task_name: harmonization

dataset:
  intensity_range: zero_one
  train:
    source_list: ./datasets/HUH/train.txt
    target_list: ./datasets/COI/train.txt
    source_root: ""
    target_root: ""
    width: 218
    height: 182
    scale_l: 0.8
    scale_h: 1.0
    transform: [h_flip]
    random_pair: false
    return_name: true
    batch_size: 1
  test:
    source_list: ./datasets/HUH/test.txt
    target_list: ./datasets/COI/test.txt
    source_root: ""
    target_root: ""
    width: 218
    height: 182
    scale_l: 1.0
    scale_h: 1.0
    transform: []
    random_pair: false
    return_name: true
    batch_size: 4

train:
  max_steps: 300000
  print_freq: 500
  image_freq: 500
  save_freq: 5000
  eval_after_train: true
  resume: false
  load_path: ""
  num_workers: 4
  amp: true
  cudnn_benchmark: true

optimizer:
  type: adam
  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0

network:
  pad_size: 10
  in_channel: 3
  out_channels: [30, 120, 480]
  weight_type: learned
  style_dim: 64
  style_base_channels: 32
  use_squeeze: false

loss:
  vgg_encoder: model/losses/vgg_model/vgg_normalised.pth
  keep_ratio: 0.9
  anatomy_weight: 1.0
  artifact_weight: 2.0

lr_scheduler:
  type: cosine
  eta_min: 0.0
